<?php echo $this->doctype(); ?>
 
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Tutorial ZF2')->setSeparator(' - ')->setAutoEscape(false) ?>
 
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
 
        <?= $this->losHeadLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependBootstrap()
            ->appendFontAwesome()
            ->appendStylesheet($this->basePath() . '/css/style.css')
        ?>
 
        <?= $this->losHeadScript()
            ->prependBootstrap()
            ->prependJquery(); ?>
 
        <?= $this->headStyle() ?>
 
    </head>
    <body>
        <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Tutorial ZF2') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php echo $this->losNavigation()->menu('Navigation')?>
                    </ul>
                </div><!--/.nav-collapse -->
 
            </div>
        </nav>
 
        <div class="container">
            <?php echo $this->losNavigation()->breadcrumbs('Navigation')?>
            <?php echo $this->losflashmessenger()->renderAll()?>
            <?php echo $this->content; ?>
        </div>
        <nav class="navbar navbar-fixed-bottom" role="navigation">
            <div class="container">
                <p class="help-block">&copy; <?php echo date('Y')?> <a href="mailto://leandro@leandrosilva.info" target="_blank">Leandro Silva</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </nav>
        <?php echo $this->inlineScript() ?>
    </body>
</html>